CREATE TABLE IF NOT EXISTS `PREFIX_chilexpress_oficial_ordermeta` (
  `id_chilexpress_oficial_ordermeta` int(11) NOT NULL AUTO_INCREMENT,
  `id_order` int(11) NOT NULL,
  `transportOrderNumber` VARCHAR(32) NOT NULL,
  `reference` VARCHAR(32) NOT NULL,
  `productDescription` VARCHAR(32) NOT NULL,
  `serviceDescription` VARCHAR(32) NOT NULL,
  `genericString1` VARCHAR(32) NOT NULL,
  `genericString2` VARCHAR(32) NOT NULL,
  `deliveryTypeCode` VARCHAR(32) NOT NULL,
  `destinationCoverageAreaName` VARCHAR(32) NOT NULL,
  `additionalProductDescription` VARCHAR(32) NOT NULL,
  `barcode` VARCHAR(32) NOT NULL,
  `classificationData` VARCHAR(32) NOT NULL,
  `printedDate` VARCHAR(32) NOT NULL,
  `labelVersion` VARCHAR(32) NOT NULL,
  `distributionDescription` VARCHAR(32) NOT NULL,
  `companyName` VARCHAR(32) NOT NULL,
  `recipient` VARCHAR(32) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `groupReference` VARCHAR(32) NOT NULL,
  `createdDate` VARCHAR(64) NOT NULL,
  `labelData` MEDIUMTEXT NOT NULL,  
  PRIMARY KEY (`id_chilexpress_oficial_ordermeta`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
